### ISSUE TITLE
Cleanup of Pipeline Driver Syntax and Documentation

### ISSUE THREAD

**Issue by blakeo2** [SEDenmarkLab/molli#139]
This is a general list of problems that I see remaining in some of the drivers. This is not a functionality issue but I think should still be resolved for homogeneity of syntax.

- In the ORCA Driver, we should decide to move the Orca parser to a separate module in the `parsing` folder of molli, that or we should move the `xtbout.py` functionality to the XTB driver 
- In the ORCA Driver`optimize_ens` method should be changed to `basic_calc_ens`, as it was above, but there's a repetition driver for some reason
- Many of the functions in the driver are lacking adequate documentation up to standard with the rest of Molli
- In the XTB Driver The `energy_m` function prep has a different name for post (`energy`), we should fix this to `energy_m`.
- We should decide if we want to add `ConformerEnsemble` versions of the functions that do not currently have them. This shouldn't be too much work since there are plenty of examples.

**Comment by esalx** [comment]
1. Orca parser definitely should go into a separate submodule
2. Why should optimize_ens be changed? I'm not sure I'm following
3. Yes, documentation is lacking. We should figure out how to add that, I'm completely swamped at the moment
4. Agreed
5. I personally don't think we should add the ConformerEnsemble version of everything in existence, but others may feel differently.

**Comment by blakeo2** [comment]
The `optimize_ens` comes after we had already defined `basic_calc_ens` using the same behavior. You can see the code in the backend, and i think for just homogeneity of function naming it should be fixed. 

On a completely separate note, an additional thing we should fix is removal of unnecessary functions in the `openbabel` driver. Many are relics from before we had more robust implementation.

**Comment by esalx** [comment]
> The `optimize_ens` comes after we had already defined `basic_calc_ens` using the same behavior. You can see the code in the backend, and i think for just homogeneity of function naming it should be fixed.

`optimize_ens` just extends `basic_calc_ens` functionality, but it does not replace it in any way. It means that we can define other functions that use `basic_calc_ens`  as a lower-level code. I still don't see any problem.

**Comment by esalx** [comment]
agree on basic_calc_ens, I see it now!
